### ISSUE TITLE
vsts-node-api

### ISSUE THREAD

**Issue by stephenmichaelf** [huserben/TfsRestService#1]
Hi! Just a heads up you may be able to use the [vsts-node-api](https://github.com/Microsoft/vsts-node-api) as a wrapper around the vsts REST endpoints. We keep it up to date with the latest API changes.

**Comment by huserben** [comment]
Hi @stephenmichaelf 

Thanks for the hint, I'll have a look when time allows :-)

**Comment by huserben** [comment]
Since the latest versions the service makes use of the _azure-devops-node-api_
